name: README build

on:
  push:
    branches:
      - main
      - workflow-playground
  schedule:
    - cron: '15 */8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
    - uses: actions/checkout@v4
    - name: Execute script
      run: php updateReadme.php
